### ISSUE TITLE
No bootstrap.sh

### ISSUE THREAD

**Issue by yeguixin** [ChrisCummins/phd#23]
When I run the install.sh in the directory: phd/docs/2018_07_issta/artifact_evaluation, I got the following error: 
--------------------------------------------------------------------------------------
+++ dirname ./install.sh
++ cd ./../../..
++ pwd
+ ROOT=/home/gxye/project/phd
+ main
+ cd /home/gxye/project/phd
+ test -f /home/gxye/project/phd/.env
+ /home/gxye/project/phd/tools/bootstrap.sh
./install.sh: line 23: /home/gxye/project/phd/tools/bootstrap.sh: No such file or directory
-------------------------------------------------------------------------------------------
I checked the target directory "./phd/tools/", and there is not bootstrap.sh, only the bootstrap.py.

**Comment by ChrisCummins** [comment]
Hi @yeguixin, sorry for the slow reply - it's a busy time for me with traveling :)

I've done some work not the artifact to make it easier to build, and fixed a few bugs like this one. I've updated the README to reflect the new build process:

https://github.com/ChrisCummins/phd/tree/master/docs/2018_07_issta/artifact_evaluation

Let me know if you have any further problems.

Cheers,
Chris

**Comment by yeguixin** [comment]
Thanks very much

**Comment by ChrisCummins** [comment]
Great!
