### ISSUE TITLE
lib.labm8.lockfile.UnableToAcquireLockError

### ISSUE THREAD

**Issue by yeguixin** [ChrisCummins/phd#26]
Hi Chris,
When I run the command "bazel run //docs/2018_07_issta/artifact_evaluation:01_evaluate_generator", got a error as follows:
-----------------------------------------------------------------------------------------------------------------
  File "/home/gxy/.cache/bazel/_bazel_gxy/45b7240206d651f2bfc82ad3534122dd/execroot/phd/bazel-out/local-opt/bin/docs/2018_07_issta/artifact_evaluation/01_evaluate_generator.runfiles/phd/lib/labm8/lockfile.py", line 173, in acquire
    raise UnableToAcquireLockError(self)
lib.labm8.lockfile.UnableToAcquireLockError: Unable to acquire file lock owned by a different process.
Lock acquired by process 6048 on gxy@localhost at 2018-07-30 05:56:28.414000.
Lock path: /tmp/phd/docs/2018_07_issta/artifact_evaluation/clgen/model/15b5ca3baf7cae9160f1f5ff3f47f8ecfe279098/LOCK
ERROR: Non-zero return code '1' from command: Process exited with status 1.
-------------------------------------------------------------------------------------------------------------------
PS：The operating system is Centos 7.5.

How to solve it. Thanks

**Comment by ChrisCummins** [comment]
Hi @yeguixin , thanks for the bug report. There is a locking mechanism to ensure that only one process modifies a tensorflow model at a time. However, if a process crashes or is cancelled, it can sometimes be that the lock doesn't get freed. If you are sure there are no other processes, you can safely remove the lock with:

```
$ rm /tmp/phd/docs/2018_07_issta/artifact_evaluation/clgen/model/15b5ca3baf7cae9160f1f5ff3f47f8ecfe279098/LOCK
```

Cheers,
Chris

**Comment by yeguixin** [comment]
Greet. It works. Thanks very much.

Cheers,
Guixin
