### ISSUE TITLE
Get an error on `bazel test //... `

### ISSUE THREAD

**Issue by llnlln** [ChrisCummins/phd#31]
Hi，Mr.Cummins
When I install the environment according to the README.md file in the phd directory, I execute `bazel test //... `The following error occurred, 
![bazel test opt](https://user-images.githubusercontent.com/32690972/46640537-35f09d00-cb9f-11e8-9f90-6fb44579d338.png)
sometimes the following error occurred, 
![docker test](https://user-images.githubusercontent.com/32690972/46640582-88ca5480-cb9f-11e8-94e3-7040b6e4b588.png)
Can you give me some advice on how to solve this problem？

**Comment by ChrisCummins** [comment]
Hi there, could you try running just a single test: `bazel test //lib/labm8:fs_test` ? There's a couple of things going on here - the first screenshot shows a broken test (which isn't too unusual - this is research/personal code), but the second screenshot shows an error in preparing the python dependencies, which is more of a concern. Running a single test will help isolate the problem.

Cheers,
Chris

**Comment by llnlln** [comment]
Thanks for your advice, I was successful when I tried to run a single test

> Hi there, could you try running just a single test: `bazel test //lib/labm8:fs_test` ? There's a couple of things going on here - the first screenshot shows a broken test (which isn't too unusual - this is research/personal code), but the second screenshot shows an error in preparing the python dependencies, which is more of a concern. Running a single test will help isolate the problem.
> 
> Cheers,
> Chris

Thanks for your advice, I was successful when I tried to run a single test

**Comment by ChrisCummins** [comment]
Do you mean the structure of the repo, or the code structure for a particular project?

**Comment by llnlln** [comment]
Hi，Mr.Cummins
     Thank you for your reply. I want to know the code structure of PhD project, so that I can understand the process of the whole project, especially the part of training model. I want to know what more work needs to be done to extend to another language. Therefore, I sincerely hope that you can offer some Suggestions to help me understand the whole project.

**Comment by ChrisCummins** [comment]
Hi, sorry for the slow reply :) It sounds like you're interested in the DL program generator. In that case, I'd suggest first looking in [//deeplearning/clgen](https://github.com/ChrisCummins/phd/tree/master/deeplearning/clgen) to get a feel for the structure. You could take a look at [deeplearning.clgen.models.backens.TensorFlowBackend.Train()](https://github.com/ChrisCummins/phd/blob/master/deeplearning/clgen/models/tensorflow_backend.py#L228-L325) to see how the Tensorflow models are trained. The [deeplearning.clgen.corpuses.corpuses.Corpus](https://github.com/ChrisCummins/phd/blob/master/deeplearning/clgen/corpuses/corpuses.py#L76) class encapsulates the training data. A general recommendation I'd suggest to start by looking at the protocol buffer definitions, as these describe the types of data which are passed between components, and how components are configured. E.g. the [clgen.Model](https://github.com/ChrisCummins/phd/blob/master/deeplearning/clgen/proto/model.proto#L17) proto.

I'm going to close this issue, but feel free to follow up with any specific questions.

**Comment by llnlln** [comment]
Thank you for your reply. May I ask how big the compressed complete data set is? Could you share the complete data set?
