### ISSUE TITLE
Erros on 'bazel test //deeplearning/clgen/...'

### ISSUE THREAD

**Issue by JiajieZhang-Georgia** [ChrisCummins/phd#33]
Hi Chris,
I run the code 'bazel test //deeplearning/clgen/...' to test the environment after installation,
but get errors as follows:
'//deeplearning/clgen/models:keras_backend_test                           FAILED in 24.1s
  /home/georgia/.cache/bazel/_bazel_georgia/03a359912ab05c7f13a1dd9a75789983/execroot/phd/bazel-out/k8-py3-opt/testlogs/deeplearning/clgen/models/keras_backend_test/test.log
//deeplearning/clgen/preprocessors:java_test                             FAILED in 1.6s
  /home/georgia/.cache/bazel/_bazel_georgia/03a359912ab05c7f13a1dd9a75789983/execroot/phd/bazel-out/k8-py3-opt/testlogs/deeplearning/clgen/preprocessors/java_test/test.log
Executed 21 out of 21 tests: 19 tests pass and 2 fail locally.'

When I check the log,
I found some errors like
'AttributeError: 'Corpus' object has no attribute 'decoder'

deeplearning/clgen/models/keras_backend.py:92: AttributeError
'
and 
'
File "/home/georgia/.cache/bazel/_bazel_georgia/03a359912ab05c7f13a1dd9a75789983/sandbox/linux-sandbox/289/execroot/phd/bazel-out/k8-py3-opt/bin/deeplearning/clgen/preprocessors/java_test.runfiles/phd/deeplearning/clgen/preprocessors/java.py", line 15, in <module>
    from lib.labm8 import bazelutil
ModuleNotFoundError: No module named 'lib.labm8'
'
Thank you.

**Comment by ChrisCummins** [comment]
Hi, sorry for the slow reply :) As you've probably discovered, the failing test cases aren't in the bits of the codebase that you should need to worry about
