### ISSUE TITLE
How to set importer field?

### ISSUE THREAD

**Issue by JiajieZhang-Georgia** [ChrisCummins/phd#34]
When I wanted to extract individual source files from the cloned repos and import them into a contentfiles database, and run the code as following:
`$ bazel run //datasets/github/scrape_repos:importer -- \
    --clone_list $PWD/clone_list.pbtxt`

I got an error said:
`/datasets/github/scrape_repos/importer.py", line 136, in ImportFromLanguage
    raise ValueError('LanguageToClone.importer field not set')
ValueError: LanguageToClone.importer field not set
`
My question is how to set the importer field.
Thank you.

**Comment by ChrisCummins** [comment]
Hi,

When you specify the languages to clone in the configuration proto, you provide a list of [importers](https://github.com/ChrisCummins/phd/blob/master/datasets/github/scrape_repos/proto/scrape_repos.proto#L33) (if you're not familiar with protobuf format, I'd recommend checking [the docs](https://developers.google.com/protocol-buffers/docs/pythontutorial)). Looks like you need to set some. 

Here's an example importer in a text format protobuf: https://github.com/ChrisCummins/phd/blob/master/experimental/deeplearning/polyglot/clone_lists/java.pbtxt#L37-L40

And here's an example importer being set from python: https://github.com/ChrisCummins/phd/blob/master/datasets/github/scrape_repos/importer_test.py#L78-L83
