### ISSUE TITLE
Support for Cuda-9.2

### ISSUE THREAD

**Issue by KostasBitsakos** [ChrisCummins/phd#38]
Hello,

current tensorflow version does not support by deafult cuda-9.2 installation.
I need to produce programs that can run both on nvidia gpus and intel cpus, using clgen.
If I configure clgen without cuda support would that be possible?

**Comment by ChrisCummins** [comment]
Hi Constandinos,

CUDA support is only needed to train CLgen models using the GPU. You do not need CUDA support to generate GPU-compatible OpenCL code, and you can train models on the CPU. Hope that helps :)

Cheers,
Chris

**Comment by KostasBitsakos** [comment]
Thanks Chris,

that was very helpful.

Cheers,
Consantinos
