### ISSUE TITLE
File 'generator_pb2' missing?

### ISSUE THREAD

**Issue by ty5491003** [ChrisCummins/phd#53]
Hi Chris, i'm a noob of this project, i have some questions.

I have seen 'generator_pb2' file used in many files, but I didn't find it anywhere. I wonder if this file is missing or is it generated during the process of building the system? (I haven't started building the system yet).

Thx:laughing:!

**Comment by ChrisCummins** [comment]
Hi Yang, yes the file generator_pb2 is generated from the protocol buffer file generator.proto by bazel. Alternatively you can compile it yourself using the protoc compiler. Hope that helps :)

Cheers,
Chris

**Comment by ty5491003** [comment]
@ChrisCummins I get it, thx!

**Comment by ChrisCummins** [comment]
Yep, currently, I only make weighted choices from the probability distribution, see:
https://github.com/ChrisCummins/phd/blob/master/deeplearning/clgen/models/tensorflow_backend.py#L377-L387

I'd be very interested to try the strategies you suggest, IIRC others have tried different strategies as well (like only sampling on whitespace, and taking argmax within words), I'd happily accept a PR! :)

Great, would love to hear about your related work! Shoot me an email at chrisc.101@gmail.com if you like

**Comment by ty5491003** [comment]
i get it, thanks for your reply.
I'll send you if I get some good results.
